version: '3'
services:
  database:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=fib
      - MYSQL_DATABASE=fib
      - MYSQL_USER=fib
      - MYSQL_PASSWORD=fib
    networks:
      - app
    expose:
      - 3306
    cap_add:
      - SYS_NICE

  backend:
    depends_on:
      - database
    build: ./backend
    volumes:
      - ./backend:/backend/app
    networks:
      - app
    ports:
      - "80:80"
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend/app
    networks:
      - app
    ports:
      - "8000:8000"

networks:
  app:
